Bugfix/155 feedback sprint 2 rutinas
ISPP-23-24-Grupo-3/musclemate-frontend pull request #176
Opened 2024-04-06 18:38 UTC by Leonidas6000

Closes #155

2024-04-07 18:20 UTC, ElenaTomasVela requested changes
Se te ha pasado cambiar un mensaje de eliminar ejercicio para que diga "Quieres quitar el ejercicio X" en vez de "Quieres quitar la rutina X".

Por cierto, veo que has quitado un componente que se usaba para simplificar la tarea de la selección de máquinas y has puesto su implementación entera de vuelta. ¿Por qué lo has hecho? No tienes por qué cambiarlo si no quieres, pero al menos me gustaría que mencionaras por qué.

2024-04-07 23:41 UTC, Leonidas6000 commented
Lo hice porque estuve probando para intentar integrar un buscador en el desplegable pero al final no la consegui poner y ya pues lo deje asi, mas adelante intentare añadir el buscador

2024-04-07 23:44 UTC, ElenaTomasVela commented
> Lo hice porque estuve probando para intentar integrar un buscador en el desplegable pero al final no la consegui poner y ya pues lo deje asi, mas adelante intentare añadir el buscador

En ese caso, te recomiendo que cambies directamente el componente, para que todos los demás sitios que necesiten escoger máquinas puedan heredar fácilmente la funcionalidad.

2024-04-07 23:45 UTC, Leonidas6000 commented
pues si la verdad, es lo que hare

2024-04-08 11:35 UTC, ElenaTomasVela approved these changes

2024-04-08 11:35 UTC, merged